### ISSUE TITLE
namespace.startsWith is not a function

### ISSUE THREAD

**Issue by franciscosucre** [adonisjs/adonis-auth#87]
Calling any route with the auth:jwt middleware produces this result since i upgraded to version 2.0.11, i'm reverting to another release but i think the giving this feedback could help. Awesome project by the way! Adonisjs is the best node framework i've used!

{
    "status": 500,
    "message": "namespace.startsWith is not a function",
    "traces": "TypeError: namespace.startsWith is not a function\n    at _.find (/home/francisco/.local/share/Trash/files/server-v2/node_modules/@adonisjs/fold/src/Ioc/index.js:119:24)\n    at baseFindIndex (/home/francisco/.local/share/Trash/files/server-v2/node_modules/lodash/lodash.js:823:11)\n    at findIndex (/home/francisco/.local/share/Trash/files/server-v2/node_modules/lodash/lodash.js:7275:14)\n    at Function.find (/home/francisco/.local/share/Trash/files/server-v2/node_modules/lodash/lodash.js:5098:21)\n    at Ioc._getAutoloadedNamespace (/home/francisco/.local/share/Trash/files/server-v2/node_modules/@adonisjs/fold/src/Ioc/index.js:118:14)\n    at Ioc._isAutoloadedPath (/home/francisco/.local/share/Trash/files/server-v2/node_modules/@adonisjs/fold/src/Ioc/index.js:163:19)\n    at Ioc.use (/home/francisco/.local/share/Trash/files/server-v2/node_modules/@adonisjs/fold/src/Ioc/index.js:724:14)\n    at Instance.handle (/home/francisco/.local/share/Trash/files/server-v2/app/Middleware/Instance.js:18:19)\n    at Server._resolveMiddleware (/home/francisco/.local/share/Trash/files/server-v2/node_modules/@adonisjs/framework/src/Server/index.js:110:28)\n    at _resolveListItem (/home/francisco/.local/share/Trash/files/server-v2/node_modules/co-compose/src/Runnable.js:50:28)\n    at dispatch (/home/francisco/.local/share/Trash/files/server-v2/node_modules/co-compose/src/Runnable.js:112:16)\n    at _.once (/home/francisco/.local/share/Trash/files/server-v2/node_modules/co-compose/src/Runnable.js:111:35)\n    at /home/francisco/.local/share/Trash/files/server-v2/node_modules/lodash/lodash.js:10067:25\n    at Auth.handle (/home/francisco/.local/share/Trash/files/server-v2/node_modules/@adonisjs/auth/src/Middleware/Auth.js:87:11)\n    at <anonymous>"
}

The endpoint that i used as an example was the following:

async upload ({ request, response, instance, auth }) {
    const user = instance
    if (String(auth.user._id) !== String(user._id)) {
      throw UnAuthorizeException.invoke()
    }
    const image = request.file('image', {
      maxSize: '2mb',
      allowedExtensions: ['jpg', 'png', 'jpeg']
    })
    const fileName = `${use('uuid').v1().replace(/-/g, '')}_${image._clientName}`
    await image.move(use('Helpers').publicPath('uploads'), { name: fileName })
    const filePath = `uploads/${fileName}`
    await user.images().create({ fileName, filePath })
    // await user.related('images').load()
    return response.apiUpdated(user)
  }

**Comment by franciscosucre** [comment]
Sorry, i played for it a little bit more and it was a problem with the boilerplate for Lucid-mongo, the instance middleware was using modelName as a string but it obtains it as an array. Sorry. Keep up the good work!
